### ISSUE TITLE
Not able to reconnect even if use --keep-reconnect 

### ISSUE THREAD

**Issue by xiangwu-ms** [wangyu-/tinyfecVPN#101]
--keep-reconnect does not work in all scenarios. 

I have a server running behind of firewall, published an UDP port, Client NAT to internet. Somehow the channel between the server and client will hang after around 12 hours. Client keep sending packets, but somehow the packets are not received by the server. The SRC:PORT session on one of the firewall/NAT device stuck. Restart the client with new SRC:PORT will recover the network. 

Can --keep-reconnect switch a new SRC:PORT so that there will be a new session established to overcome this firewall/NAT issue?

**Comment by xiangwu-ms** [comment]
Please ignore this request. I will try Udp2raw

**Comment by wangyu-** [comment]
> I will try Udp2raw

correct. chain udp2raw into you connection.

The heartbeat detect and auto change port is implemented in udp2raw.  The same feature is not implemented again in tinyfecVPN.
