### ISSUE TITLE
ss+tunyfecvpn+udp2raw双倍延迟的问题

### ISSUE THREAD

**Issue by PHCSJC** [wangyu-/tinyfecVPN#104]
我的配置是这样的：ss+tunyfecvpn+udp2raw，测试如下：
1.ping 10.22.22.1的迟延是200ms
2.服务器端启动ss，端口是1234，在客户端tcpping  10.22.22.1 1234，延迟是200ms，说明本地到ss服务端延迟也是200ms
3.本地配置好ss和iptables redirect，ss连10.22.22.1，可以正常上外网，说明通是没问题的
4.iptables配置好8.8.8.8的redirect，用dig youtube.com @8.8.8.8 +tcp测试，延迟是400ms，问题就出在这，变双倍了
5.给ss的两端都加上--fast-open参数，dig的延迟变正常了，是200ms。

总结问题就是：在ss+tunyfecvpn+udp2raw配置下，如果ss不加--fast-open参数，就是双倍延迟

另外，我也有测试ss+kcptun+udp2raw这样的配置，不用加--fast-open参数也没问题，不会出现双倍延迟的问题。

再就是，ss+kcptun+udp2raw其实已经挺稳定，用ss+tunyfecvpn+udp2raw，主要是因为速度更快，我实测快70%左右，所以希望大佬能看看原因，是tunyfecvpn要加什么参数吗？

**Comment by wangyu-** [comment]
你测试方法有问题

>ss+kcptun+udp2raw这样的配置

这种情况下 tcp连接是本地的。 不用跟远端做3-way-handshake。  流量走kcptun的mux，不用建立新连接。
> ss+tunyfecvpn+udp2raw配置下

这种情况每个新tcp连接ss都要通过vpn做handshake。

**Comment by PHCSJC** [comment]
感谢up 2年后的解答~~

**Comment by wangyu-** [comment]
当时看了一眼，并没看出什么问题。
最近想清理一下以前的issue，重新看了一眼。
