### ISSUE TITLE
咨询一下这个程序支持最大并发链接是多少？还有支持多个端口负载均衡不

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/tinyfecVPN#111]
English Only (except for bug reporting).

**Comment by wangyu-** [comment]
vpn承载的是ip，上层不管有多少tcp连接对vpn来说没有区别。 理论上瓶颈是数据总量，跟连接数关系不大。

proxy做负载均衡还可以理解，不知道在vpn语义下你怎么定义多端口负载均衡。
