### ISSUE TITLE
Openwrt, redirect-gateway, Windows.

### ISSUE THREAD

**Issue by Onair-santa** [wangyu-/tinyfecVPN#112]
Need redirect-gateway and solution for Openwrt and Windows(non virtual machine). 
It would be very good

**Comment by wangyu-** [comment]
if you really need this, use wireguard +udpspeeder.
tinyfecVPN is only a tiny one that embeds the udpspeeder. For more function and cross-platform, use udpspeeder with a heavier vpn solution.
