### ISSUE TITLE
FEC加速依然存在突发性丢包延迟情况

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/tinyfecVPN#114]
我这边在国内到国外分别对接了4个IP，分别用隧道 tun0 tun1 tun2 tun3 

172.16.1.2 参数  --mode 0  -q1 
172.16.2.2 参数  --mode 0   -i 20 
172.16.3.2 参数  --mode 0  -q1
172.16.4.2 参数  --mode 0  --timeout 10
只要互联网波动，出口拥塞，依然存在间歇性丢包，偶发性丢包，突发性丢包情况，无法彻底遏制，这种有没有好的办法解决？
![image](https://user-images.githubusercontent.com/55315920/229757565-9b08c6b0-95e5-49ea-859b-c94a2c631e09.png)

**Comment by wangyu-** [comment]
如果你的网抽了 一下几秒内的包全都丢了 那神仙也救不回来
