### ISSUE TITLE
After testing, it was found that the VPN tunnel does not support VXLAN and IP_GRE

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/tinyFecVPN#118]
provided scenario involves creating a virtual network between two hosts (A and B) using VXLAN. 

On host A (assuming 172.16.71.2 with tun1 interface):
```
ip link add vxlan71 type vxlan id 71 remote 172.16.71.1 local 172.16.71.2 dstport 4789 dev tun1
ip addr add 172.16.171.2/32 dev vxlan71
ip link set vxlan71 up
ip route add 172.16.171.0/24 dev vxlan71
```

On host B (assuming 172.16.71.1 with tun1 interface):
```
ip link add vxlan71 type vxlan id 71 remote 172.16.71.2 local 172.16.71.1 dstport 4789 dev tun1
ip addr add 172.16.171.1/32 dev vxlan71
ip link set vxlan71 up
ip route add 172.16.171.0/24 dev vxlan71
```

 When trying to ping 172.16.171.1 from A, the ping is not successful.
![image](https://github.com/wangyu-/tinyfecVPN/assets/55315920/3f0bd864-309a-4149-86fb-31521f35c222)

**Comment by wangyu-** [comment]
(I am not really familiar with vxlan)

But seems like you are using the same ip as both underlay ip (tinyfecvpn) and overlay ip(vxlan)?

likely it's your configuation problem.

**Comment by maojianyou** [comment]
> (I am not really familiar with vxlan)
> 
> But seems like you are using the same ip as both underlay ip (tinyfecvpn) and overlay ip(vxlan)?
> 
> likely it's your configuation problem.

I have a scenario where server A has a physical network interface eth0 with IP address 192.168.3.100, and a public server B has a physical network interface eth0 with IP address 60.174.135.186. They are connected via a VPN created using tinyfecvpn. On server A, the tinyfecvpn interface tun0 has IP address 172.16.71.2, and on server B, the tinyfecvpn interface tun0 has IP address 172.16.71.1. I use tinyfecvpn as the underlying network to establish a VXLAN. Since 172.16.71.2 and 172.16.71.1 are part of the tinyfecvpn VPN tunnel, they can communicate with each other. The VXLAN address range is 172.16.171.2 and 172.16.171.1, which do not conflict, but they cannot communicate with each other. I will experiment further to verify this. My main goal is to achieve Layer 2 communication, as VXLAN and IP_GRE can enable Layer 2.

Additionally, I am wondering if there are any plans for the software to support Layer 2 in the future, as this would allow for VLAN splitting. Furthermore, will there be support for MPTCP (Multipath TCP) and MPQUIC (Multipath QUIC) in the future? Since TCP uses a five-tuple, the return path of a data stream from a foreign country to the domestic network is generally consistent. If there is significant congestion along this path, resulting in poor network quality, it can affect the speed and bandwidth stability when accessing overseas video content, causing buffering and slowdowns.

I have also tried setting up multiple channels and implementing routing load balancing. However, with three channels, if one becomes unstable, it can affect the others, even if the other two are fine. This can only partially mitigate the issue. With MPTCP support, even if one channel becomes unstable, maintaining TCP streams across three channels would avoid such issues. A single TCP stream could achieve load balancing across three channels.

**Comment by maojianyou** [comment]
> (I am not really familiar with vxlan)
> 
> But seems like you are using the same ip as both underlay ip (tinyfecvpn) and overlay ip(vxlan)?
> 
> likely it's your configuation problem.
