### ISSUE TITLE
Can it support MultiPath TCP (MPTCP)?

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/tinyFecVPN#122]
Suppose I have a system A and a system B, both running Debian, and I set up tunnels tun1 and tun2 between them using this software. If both A and B activate the MPTCP module and initiate load balancing on tun1 and tun2, a problem arises. A single TCP stream can only travel through one tunnel, such as tun1, which may have limited bandwidth of only 1Mbps, leading to poor network performance. However, I have another 1Mbps available on tun2. If the tunnel was capable of supporting MPTCP, then the single TCP flow could utilize both tun1 and tun2 simultaneously. Would this setup be supported?

**Comment by wangyu-** [comment]
tinyfecvpn：
1. sends udp packet
2. encapsulats IP packet

there is nothing tinyfecVPN can utilize from MPTCP IMO.

In other words. MPTCP can run inside tinyfecVPN, but tinyfecVPN cannot run on top of MPTCP.
