### ISSUE TITLE
wireguard与openvpn稳定性的是否有差别

### ISSUE THREAD

**Issue by thisdk** [wangyu-/tinyFecVPN#125]
作者你好, 感谢写出这么强大的工具.

我自建加速器从pubg时代至今.断断续续也有好几年了.

都是 ss -> kcptun -> udp2raw 或者 wg -> udpspeeder -> udp2raw 甚至试过 ss -> kcptube -> udp2raw

但是效果都不理想.一天总会掉线一两次.

直到4月底,重新审视tinyfecVPN这个项目.(虽然好几年前就知道.但是一直没尝试过) , 还是决定把心一横,尝试一下.

好在我有软路由.之前的各种加速器都放在软路由上,所以用tinyfecVPN没有任何不适,还是很轻松就搭建完成.

且碰巧,在查看tinyfecVPN文档.又看到了udpspeeder的fec的1:3,2:4,8:6,20:10这种形式的写法.同时用上了.

突然风平浪静的..这两个月每天挂机超过20个小时.2个月仅仅掉线2次.效果拔群.

至今不确定,到底是tinyfecVPN这个强,还是1:3,2:4,8:6,20:10这个fec参数厉害

但是引出一个问题.因为是在太稳定了.我想给朋友用,但是朋友没有软路由这种东西.且虚拟机感觉又像杀鸡用牛刀..

所以问问.如果使用 wg -> udpspeeder -> udp2raw 加上 1:3,2:4,8:6,20:10 参数.从技术角度来说.有没有可能和tinyfecVPN达到一样的稳定性呢?

**Comment by wangyu-** [comment]
1:3,2:4,8:6,20:10 主要效果还是省流量，跟稳定性关系应该不大。

>都是 ss -> kcptun -> udp2raw 或者 wg -> udpspeeder -> udp2raw 甚至试过 ss ->
kcptube -> udp2raw

你用这些不稳定可能是运营商对udp2raw支持不好

> 所以问问.如果使用 wg -> udpspeeder -> udp2raw 加上 1:3,2:4,8:6,20:10
参数.从技术角度来说.有没有可能和tinyfecVPN达到一样的稳定性呢?

我不是很明白为什么你用tinyfecVPN时候都没提用udp2raw 用wg+udpseeder时候却都提了udp2raw
。不知道你tinyfecvpn是不是也用了udp2raw。 如果用tinyfecvpn时候没用udp2raw， 那其他时候你也可以考虑不用udp2raw

理论上wg -> udpspeeder  跟tinyfecVPN效果一样。 实现上可能细节有区别，不好判断，建议以实际测试为准。

**Comment by thisdk** [comment]
> 1:3,2:4,8:6,20:10 主要效果还是省流量，跟稳定性关系应该不大。

以前用kcptun的时候,会手动改fec参数为多倍发包, 一般都是 2 : 4这种

而使用udpspeeder , 也会根据文档使用游戏推荐参数 2:4

这次是首次使用 1:3,2:4,8:6,20:10 这种形式 , 但是实在太稳了.

> 我不是很明白为什么你用tinyfecVPN时候都没提用udp2raw 用wg+udpseeder时候却都提了udp2raw

tinyfecVPN 看过文档 知道内部是 openvpn + udpspeeder , 所以我也套上了udp2raw 

> 理论上wg -> udpspeeder  跟tinyfecVPN效果一样。 实现上可能细节有区别，不好判断，建议以实际测试为准。

好,主要是懒,因为老祖宗传下的能跑就不要动的名言深入骨髓 , 有空把镜像改一下重新换1:3,2:4,8:6,20:10参数搭建测试一下 :)

因为从1月到3月就是wg -> udpspeeder -> udp2raw , 且存在掉线行为 , 才让我以为 openvpn在某些地方比wg有特殊优化

感谢大佬抽空回答疑问

**Comment by wangyu-** [comment]
我可不是真的推荐2:4， 2:4只是推荐给刚用的人做为一个尝试的起点。 根本就不存在适合所有人的参数。

如果你都折腾好几年了，建议看wiki上文章弄懂原理，根据自己网络情况设置参数。

另外windows上udp2raw不如linux上的稳定。

**Comment by thisdk** [comment]
> 如果你都折腾好几年了，建议看wiki上文章弄懂原理，根据自己网络情况设置参数。

以前改过很多参数.比如udp2raw 的buff , udpspeeder的fec改2:8这种 

但是一直不知道如何知道这些参数是正优化还是负优化的.只能通过是否掉线来判断.

且无论怎么改,把时间拉长到周, 每天12个小时在线来算,总会出现一周3-7次掉线.

甚至得出一个结论 , 再好的技术不如一个好的线路

> 另外windows上udp2raw不如linux上的稳定。

因为我的加速器给好几个人用的.他们确实都是windows系统的,且大部分掉线的反馈都是他们提供的.

**Comment by wangyu-** [comment]
>但是一直不知道如何知道这些参数是正优化还是负优化的.只能通过是否掉线来判断.

我说的弄懂原理是： 你自己抓包看，或者写测试程序打印出丢包pattern。 搞懂rs code原理。 

>甚至得出一个结论 , 再好的技术不如一个好的线路

这话不一定是错的：

你花高价买专线那肯定效果非常好；如果线路很差短短续续那神仙也救不了。

fec只能把你的线路在一定范围内变好，给你降低成本。花少的钱让线路达到一个不错的质量。

这话又有明显的问题：

说得好像是技术和线路是互斥的。用了一个就不能用另一个了？ 明明是两者结合着用帮你省钱。

**Comment by wangyu-** [comment]
我的issue template明明是写了english only。

只是看你后面说的可能会误导别人，所以又多说了一句。

可能我一开始就不应该回这个issue。

**Comment by thisdk** [comment]
> fec只能把你的线路在一定范围内变好，给你降低成本。花少的钱让线路达到一个不错的质量。

这个确实,因为我是廉价vps的忠实粉丝,如果不用任何您的黑科技情况下甚至没法做到1小时不掉线.

因为线路的丢包率在晚高峰能到达4%,如果单纯使用梯子协议甚至没法正常玩.这个是测试过的

发这个issue的纯粹是因为tinyfecVPN实在太稳了.让我生出了您是不是在tinyfecVPN夹带了什么黑科技的想法:)

> 我的issue template明明是写了english only。
> 只是看你后面说的可能会误导别人，所以又多说了一句。
> 可能我一开始就不应该回这个issue。

最后感谢大佬百忙之中抽出时间回答我的疑惑!!!
