### ISSUE TITLE
Can the kernel support MPTCP, like Shadowsocks-rust does, and are there similar technologies like kcp MPQUIC, etc., that are supported as well?

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/tinyFecVPN#126]
For example, if I have a small bandwidth but multiple lines like eth0, eth1, eth2, eth3, each with 2M bandwidth, can I aggregate the bandwidth of the 4 lines? Currently, MPTCP only supports TCP multipath, but can MPQUIC achieve multipath over UDP and enable bandwidth aggregation?

**Comment by wangyu-** [comment]
I have considered this before, but decided not to implement this.  Since link aggregate is complex and there is no general solution.  Since there is no general solution, it need to be done carefully by a case-by-case fashion.  Since it need to be done by a case-by-case fashion,  in the end of day I will likely spend my time on fine-tuning for a few user's very specific use cases (it's not a good way of using time).

Here I am re-using some comments I previously sent to someone in private:

>I have considered doing this before, but gave up since I couldn't find a perfect design that covers all use cases elegantly.
 
>Suppose you have a 1000mbps 10ms link and a 10mbps 100ms link, to eliminate out-of-order, you will get a 1010mbps 100ms link.

>Suppose you have a 10mbps which loses connection randomly every minute and a stable link with 1000mbps with no packet loss and no connection loss. If you bond them together, you will get a 1010mbps unstable link.

>Suppose you have 2 links with bandwidth varying from 10mbps-1000mps dynamically. It's hard to correctly bond and load balance between them since bandwidth detection will have a lag. Also it's awkward to do the bandwidth/congestion detection at layer3, while tcp is also doing it at layer4.

>As a result I believe the link aggregation needs to be carefully done in a case-by-case fashion, there is not a way that "simply works".

**Comment by wangyu-** [comment]
I have considered doing link aggreation in tinyfecVPN/UDPspeeder before, but decided not to implement this, since link aggregate is complex and there is no general solution.  Since there is no general solution, it need to be done carefully by a case-by-case fashion.  Since it need to be done by a case-by-case fashion,  in the end of day I will likely spend my time on fine-tuning for a few user's very specific use cases (it's not a good way of using time).

Here I am re-using some comments I previously sent to someone in private:

>I have considered doing this before, but gave up since I couldn't find a perfect design that covers all use cases elegantly.
 
>Suppose you have a 1000mbps 10ms link and a 10mbps 100ms link, to eliminate out-of-order, you will get a 1010mbps 100ms link.

>Suppose you have a 10mbps which loses connection randomly every minute and a stable link with 1000mbps with no packet loss and no connection loss. If you bond them together, you will get a 1010mbps unstable link.

>Suppose you have 2 links with bandwidth varying from 10mbps-1000mps dynamically. It's hard to correctly bond and load balance between them since bandwidth detection will have a lag. Also it's awkward to do the bandwidth/congestion detection at layer3, while tcp is also doing it at layer4.

>As a result I believe the link aggregation needs to be carefully done in a case-by-case fashion, there is not a way that "simply works".

For you question of MPQUIC,  I am not familiar with it. But I think the idea of link aggregation doesn't work super well in general.

**Comment by maojianyou** [comment]
> I have considered doing link aggreation in tinyfecVPN/UDPspeeder before, but decided not to implement this, since link aggregate is complex and there is no general solution. Since there is no general solution, it need to be done carefully by a case-by-case fashion. Since it need to be done by a case-by-case fashion, in the end of day I will likely spend my time on fine-tuning for a few user's very specific use cases (it's not a good way of using time).
> 
> Here I am re-using some comments I previously sent to someone in private:
> 
> > I have considered doing this before, but gave up since I couldn't find a perfect design that covers all use cases elegantly.
> 
> > Suppose you have a 1000mbps 10ms link and a 10mbps 100ms link, to eliminate out-of-order, you will get a 1010mbps 100ms link.
> 
> > Suppose you have a 10mbps which loses connection randomly every minute and a stable link with 1000mbps with no packet loss and no connection loss. If you bond them together, you will get a 1010mbps unstable link.
> 
> > Suppose you have 2 links with bandwidth varying from 10mbps-1000mps dynamically. It's hard to correctly bond and load balance between them since bandwidth detection will have a lag. Also it's awkward to do the bandwidth/congestion detection at layer3, while tcp is also doing it at layer4.
> 
> > As a result I believe the link aggregation needs to be carefully done in a case-by-case fashion, there is not a way that "simply works".
> 
> For you question of MPQUIC, I am not familiar with it. But I think the idea of link aggregation doesn't work super well in general.

It’s actually similar to the MPTCP feature in shadowsocks-rust. Shadowsocks-rust just calls the kernel’s built-in support for MPTCP, so it doesn't directly handle the multipath implementation itself. In the configuration for shadowsocks-rust, you just add the --tcp-multipath parameter, and the kernel takes care of the MPTCP multi-path feature. I’ve tested this myself: let’s say you have two tunnels, tun1 and tun2. If tun1 is throttled, meaning it's unstable and only provides around 10Mbps, and tun2 offers 50Mbps, using layer 3 static route load balancing between tun1 and tun2 doesn’t really help. For example, if a user's request goes through tun1, the speed will always be limited to tun1's 10Mbps, even though tun2 can offer much faster speeds. And if after some time tun1 improves to, say, 60Mbps, the static load balancing won’t automatically adjust.

By using the kernel's built-in MPTCP feature together with shadowsocks-rust’s MPTCP support, you can dynamically combine the speeds. This means download speeds could vary between 30-60Mbps, rather than being stuck at tun1's 10Mbps. This happens because the MPTCP setup allows dynamic aggregation of the tunnel speeds, which solves the problem of a single TCP flow being stuck on one specific tunnel. Without MPTCP, a single TCP stream would always be limited to one tunnel's speed. That’s especially frustrating for activities like playing overseas games or streaming 4K videos. If speeds don’t add up, streaming 4K content could become choppy and laggy.

I see that shadowsocks-rust directly calls the kernel's IPPROTO_MPTCP parameter. The actual MPTCP functionality can be implemented using the kernel's built-in support for MPTCP, so the software itself doesn't need to include complex multi-path code.
![image](https://github.com/user-attachments/assets/b298a6fc-ea8b-4d2c-8aab-d7a320da4466)

![image](https://github.com/user-attachments/assets/ad34be7b-e9bb-4390-9743-dec07b984ddb)

![image](https://github.com/user-attachments/assets/017bbe0e-fb9e-46c7-af97-bdfc61b5528b)

This is the final test result I got by using your VPN software with the tun1 and tun2 tunnels, combined with the MPTCP support in shadowsocks-rust. The speed and stability did indeed improve. If your software natively supported MPTCP by calling the kernel's MPTCP, I wouldn’t need to deploy shadowsocks-rust anymore. Your software would be perfect.
![image](https://github.com/user-attachments/assets/57d6f8ae-6fec-4580-8a21-90ca131a1d0f)

Before acceleration
![image](https://github.com/user-attachments/assets/638bd8e7-3e12-4e00-9734-81b074c71a56)


After acceleration
![image](https://github.com/user-attachments/assets/32e9e7b1-b320-41cd-9861-c6378756092a)

**Comment by wangyu-** [comment]
the user case of tinyfecvpn and shadowsocks is different.
shadowsocks typically aims for tcp traffic,  especially combined with mptcp
tinyfecvpn is:
1. tunnels any protocol >= ip layer, 
2.  latency-sensitive.
3.  packet deliver order matters. (if one link has smaller latency, the other link has large latency, it will case nightmare for some udp protocols)

you might got some improvement on download speed if involve multiple path, but it will cause decrease in other aspect. 
So far all your data is pointing to download speed. If you only cares your tcp download speed, doesn't care other aspects much,  in this case maybe simply go ahead and use shadowsocks-rust +mptcp. 

technique-wise:
QUIC's main use case is TCP-Like stream delivery, although QUIC supports datagram by the way. Not sure how well MPQUIC works for datagram. From my analysis in previous post, I don't think MPQUIC can work magiclly well for tinyfecvpn.

implementation-wise:
Also MPQUIC is userspace programs, it's not going to be as simple as IPPROTO_MPTCP.

**Comment by maojianyou** [comment]
> the user case of tinyfecvpn and shadowsocks is different. shadowsocks typically aims for tcp traffic, especially combined with mptcp tinyfecvpn is:
> 
> 1. tunnels any protocol >= ip layer,
> 2. latency-sensitive.
> 3. packet deliver order matters. (if one link has smaller latency, the other link has large latency, it will case nightmare for some udp protocols)
> 
> you might got some improvement on download speed if involve multiple path, but it will cause decrease in other aspect. So far all your data is pointing to download speed. If you only cares your tcp download speed, doesn't care other aspects much, in this case maybe simply go ahead and use shadowsocks-rust +mptcp.
> 
> technique-wise: QUIC's main use case is TCP-Like stream delivery, although QUIC supports datagram by the way. Not sure how well MPQUIC works for datagram. From my analysis in previous post, I don't think MPQUIC can work magiclly well for tinyfecvpn.
> 
> implementation-wise: Also MPQUIC is userspace programs, it's not going to be as simple as IPPROTO_MPTCP.

I’m currently using TinyFecVPN at the IP layer because it supports FEC. I looked into KCPTun, but it’s a bit inconvenient since it doesn’t support TUN interfaces and only works in one direction. Your software is great, offering bidirectional acceleration. I set the FEC to 20:20, which consumes more bandwidth, but provides better stability. However, I’ve noticed an issue when watching 4K at 60fps at home; it sometimes lags. I found out it’s because a single TCP data stream is routed through just the tun1 tunnel. For example, I have 6 tunnels: tun1, tun2, tun3, tun4, tun5, and tun6, and they’re used for Layer 3 load balancing.

The current solution I’ve implemented is deploying Shadowsocks-rust + MPTCP over these six tunnels. The data still travels through TinyFecVPN at the lower level, using UDP + FEC for acceleration. I’ve set up the TinyFecVPN server and client with three destination IPs: tun1 and tun2 use one, tun3 and tun4 use another, and tun5 and tun6 use the third one. Each destination IP is also divided into two target ports. This setup helps avoid TCP speed limits on individual TCP streams at real international internet gateways. Since I’m also using udp2raw at the bottom, the network routers and switches think the packets are from a single TCP stream, so I created multiple tunnel interfaces to achieve multipath.

If TinyFecVPN can’t support MPTCP directly, I’ll just keep using my current setup by layering Shadowsocks-rust + kernel MPTCP on top of TinyFecVPN for bandwidth aggregation. Once again, thank you for this excellent VPN software!
