### ISSUE TITLE
Currently, only the TUN interface is supported, and this interface operates at Layer 3. Is it possible to implement Layer 2 support similar to OpenVPN's TAP interface?

### ISSUE THREAD

**Issue by maojianyou** [wangyu-/tinyFecVPN#127]

**Comment by wangyu-** [comment]
if you need, you can run a vx-lan overlay on-top of tinyfecvpn, similiar to what is did in a comment here:

https://github.com/wangyu-/udp2raw/issues/526

**Comment by maojianyou** [comment]
> if you need, you can run a vx-lan overlay on-top of tinyfecvpn, similiar to what is did in a comment here:
> 
> https://github.com/wangyu-/udp2raw/issues/526

I have tested VXLAN, and it works. What I was thinking before was to avoid repeated nesting.
