### ISSUE TITLE
仅支持一个client连接？

### ISSUE THREAD

**Issue by helloxz** [wangyu-/tinyFecVPN#13]
> TinyFecVPN server只接受一个client的连接，后连接的client会把新的挤掉。

请问有办法支持多个client连接吗？
比如我服务器上有443和445端口
client1 走443，client 2走445，能实现吗？

**Comment by wangyu-** [comment]
开两个server就可以了

**Comment by helloxz** [comment]
如我希望使用client，这样写对否？仅改变udp（4097）监听端口和内网地址（10.22.23.0）？
server：
```
./tinyvpn -s -l0.0.0.0:4097 -f20:10 -k "passwd" --sub-net 10.22.23.0
```
然后client
```
./tinyvpn -c -r44.55.66.77:4097 -f20:10 -k "passwd" --sub-net 10.22.23.0
```
然后client使用10.22.23.1来加速？

**Comment by helloxz** [comment]
测试client 2连接的时候不行

**Comment by wangyu-** [comment]
我测试了，没有问题。你根据自己的环境自己解决一下吧。

**Comment by helloxz** [comment]
应该是我IP写错了，麻烦了。
