### ISSUE TITLE
怎么编译成 Server 模式？

### ISSUE THREAD

**Issue by bao3** [wangyu-/tinyFecVPN#14]
我发现你所有的项目都没有写编译方式和依赖，看得都一头雾水，而这个项目则是没说明怎么能编译没有限制的 Server 模式。

**Comment by wangyu-** [comment]
>我发现你所有的项目都没有写编译方式和依赖，看得都一头雾水

https://github.com/wangyu-/udp2raw-tunnel/blob/master/doc/README.zh-cn.md#如何自己编译

https://github.com/wangyu-/UDPspeeder/blob/master/doc/README.zh-cn.md#编译教程

其他项目一样。

>而这个项目则是没说明怎么能编译没有限制的 Server 模式

这个只能自己看代码解决。
