### ISSUE TITLE
不支持windows?

### ISSUE THREAD

**Issue by zhengoogle** [wangyu-/tinyFecVPN#18]
没有支持windows的release版本吗

**Comment by wangyu-** [comment]
readme里明确说了，只支持linux，windows可以用虚拟机。

**Comment by wangyu-** [comment]
或者弄个linux路由器。tinyFecVPN运行在路由器上，把网络分享给windows。

**Comment by jonwinters** [comment]
有空可以移植下，主要是windows下用c语言 操作tun/tap 文档少的可怜
