### ISSUE TITLE
可否提供mac下面的客户端程序？

### ISSUE THREAD

**Issue by luckypoem** [wangyu-/tinyFecVPN#19]
非常感谢

**Comment by wangyu-** [comment]
以后会有。不过这个事的优先级不高。

我建议你搞个linux路由器，把tinyFecVPN运行在路由器上，这样windows/mac/android/ios/游戏主机 全支持。就不用等了。

**Comment by luckypoem** [comment]
HI.
但是我不熟悉linux路由器（我在linux路由器上暂未安装openwrt),所以可否提供mac下面的客户端程序呢？
非常感谢～

**Comment by wmjlxl** [comment]
今天尝试用 macbook pro m1 max 来编译，但是出现好多错误。
不知道怎么解决。求大侠 @wangyu-  帮忙解决。


~ make nolimit
make OPT=-DNOLIMIT
echo "const char * const gitversion = \"cd4973c36fb75fb0d84241987febea41eee43611\";" > git_version.h
rm -f tinyvpn
g++   -o tinyvpn        `ls UDPspeeder/*.cpp UDPspeeder/lib/*.cpp|grep -v main.cpp|grep -v tunnel.cpp` main.cpp tun_dev.cpp tun_dev_client.cpp tun_dev_server.cpp -std=c++11   -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -Wno-missing-field-initializers -ggdb -I. -IUDPspeeder -isystem UDPspeeder/libev -DNOLIMIT  -lrt -ggdb -static -O3
UDPspeeder/tunnel_client.cpp:45:41: warning: suggest braces around initialization of subobject [-Wmissing-braces]
                address_t::storage_t udp_new_addr_in={0};
                                                      ^
                                                      {}
1 warning generated.
UDPspeeder/tunnel_server.cpp:142:40: warning: suggest braces around initialization of subobject [-Wmissing-braces]
        address_t::storage_t udp_new_addr_in={0};
                                              ^
                                              {}
1 warning generated.
In file included from main.cpp:11:
./tun_dev.h:11:9: warning: 'NOLIMIT' macro redefined [-Wmacro-redefined]
#define NOLIMIT
        ^
<command line>:1:9: note: previous definition is here
#define NOLIMIT 1
        ^
In file included from main.cpp:11:
./tun_dev.h:22:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
In file included from tun_dev.cpp:9:
./tun_dev.h:11:9: warning: 'NOLIMIT' macro redefined [-Wmacro-redefined]
#define NOLIMIT
        ^
<command line>:1:9: note: previous definition is here
#define NOLIMIT 1
        ^
In file included from tun_dev.cpp:9:
./tun_dev.h:22:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
In file included from tun_dev_client.cpp:1:
./tun_dev.h:11:9: warning: 'NOLIMIT' macro redefined [-Wmacro-redefined]
#define NOLIMIT
        ^
<command line>:1:9: note: previous definition is here
#define NOLIMIT 1
        ^
In file included from tun_dev_client.cpp:1:
./tun_dev.h:22:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
In file included from tun_dev_server.cpp:1:
./tun_dev.h:11:9: warning: 'NOLIMIT' macro redefined [-Wmacro-redefined]
#define NOLIMIT
        ^
<command line>:1:9: note: previous definition is here
#define NOLIMIT 1
        ^
In file included from tun_dev_server.cpp:1:
./tun_dev.h:22:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^~~~~~~~~~~~
1 warning and 1 error generated.
make[1]: *** [all] Error 1
make: *** [nolimit] Error 2



![CleanShot 2023-02-03 at 2 PM 05 05@2x](https://user-images.githubusercontent.com/22372603/216525006-7fcc52e9-f1b6-4889-84d9-e0d25fba4f1b.png)

**Comment by wangyu-** [comment]
@wmjlxl tinyfecvpn估计不会出mac和windows版了，tun设备跨平台比较麻烦。

推荐用wireguard + UDPspeeder， 跟tinyfecvpn功能是一样的。
