### ISSUE TITLE
ubuntu 使用tinyFecVpn + udp2raw,无法访问海外网站

### ISSUE THREAD

**Issue by ssgoogle** [wangyu-/tinyFecVPN#20]
首先感谢大佬的贡献！

客户端运行环境：ubuntu16.04
运行以下命令
tinyvpn_amd64 -c -r192.168.1.100:4096 -f20:10 -k "passwd" --sub-net 10.22.22.0 --tun-dev tun100
udp2raw_amd64_hw_aes -c -rxx.xx.xx.xx:8855 -l0.0.0.0:4096 --raw-mode faketcp -a -k"passwd"
(xx.xx.xx.xx 服务器地址)
ip route add 0/1 dev tun100

服务器环境:ubuntu 17.04 (新安装)
运行以下命令
udp2raw_amd64_hw_aes -s -l0.0.0.0:8855 -r 127.0.0.1:4096  -a -k"passwd" --raw-mode faketcp
echo 1 >/proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -s 10.22.0.0/16 -j SNAT --to-source xx.xx.xx.xx (服务器地址)
tinyvpn_amd64 -s -10.0.0.0:4096 -f20:10 -k "passwd" --sub-net 10.22.22.0 --tun-dev tun100

以上配置可以访问百度，v2,可以访问淘宝美国站，github.客户的浏览器确认ip地址也显示是服务器地址
但是访问不了其他海外网站。

tinyvpn+＄＄ udp relay（部署在路由器上） 可以访问海外网站
单独使用tinyvpn的话，ssh会掉。加上udp2raw，ssh就稳定了

是不是路由器的路由有问题了？

**Comment by wangyu-** [comment]
`ip route add 0/1 dev tun100`

这条的用意是什么，为什么只添加了0.0.0.0/1，而没有添加128.0.0.0/1。

>以上配置可以访问百度，v2,可以访问淘宝美国站，github.客户的浏览器确认ip地址也显示是服务器地址
但是访问不了其他海外网站。

有没有设置过DNS为8.8.8.8?  除了前面提到的问题，可能还有DNS污染的问题。

**Comment by ssgoogle** [comment]
128.0.0.0/1这条漏写了，抱歉。
路由器的路由是默认设置，刚刚也确认过了，在客户的设定DNS吗，我没设置

**Comment by ssgoogle** [comment]
就是DNS的问题，设置后就可以了。exciting，再次感谢！
