### ISSUE TITLE
能否直接在服务器上安装？

### ISSUE THREAD

**Issue by elric8** [wangyu-/tinyFecVPN#21]
我看了一下wiki
当中提到了作者您人为的加了限制
不能用来翻墙
我现在想加速游戏
能否直接在我的海外vps上运行连接到我的merlin路由器上
谢谢！

**Comment by wangyu-** [comment]
如果你想要直接通过tinyFecVPN访问游戏，需要自己编译server端。

如果你只是想用tinyFecVPN加速VPS上的s***，那么不需要自己编译，直接用releases里的就可以。

**Comment by elric8** [comment]
> 如果你想要直接通过tinyFecVPN访问游戏，需要自己编译server端。

如果你只是想用tinyFecVPN加速VPS上的s***，那么不需要自己编译，直接用releases里的就可以。

好，谢谢看来不会编译。。。只能无缘了
