### ISSUE TITLE
这个跟zerotier有什么区别吗？

### ISSUE THREAD

**Issue by cfcboy** [wangyu-/tinyFecVPN#22]
刚了解内网穿透，试了zerotier感觉还不错，说用的是P2P。实测下来确实速度非常快。

你这个软件还没有测试，但是看你的测试数据感觉应该不差。

建议：能不能集合zerotier的优点：1.多客户端 2.有管理界面（方便知道客户的IP，管理等）

zerotier必须有中心点（好像可以自建moon），你这个是直连方式。

**Comment by cfcboy** [comment]
tinyFecVPN的IP是自动分配的吗？能不能加一个自定IP的功能。

**Comment by wangyu-** [comment]
tinyFecVPN是加速器。你说的那个软件我没用过，但是看你的描述，这两者应该没有可比性。

>tinyFecVPN的IP是自动分配的吗？能不能加一个自定IP的功能。

可以自己指定ip的前三位，但是最后一位是固定的，不能修改。

**Comment by cfcboy** [comment]
--sub-net

指定VPN的子网，格式为xxx.xxx.xxx.0。 例如: 对于--sub-net 10.10.10.0, server的IP会被设置成10.10.10.1,client的IP会被设置成10.10.10.2 .

server的ip自动为1，client1为2，那client2的ip是不是为3，默认递增的吗？

建议，能不能client端自己设置IP，或者server端给不同的client端指定固定IP，这样方便多client客户端的时候，好标识，管理。

**Comment by cfcboy** [comment]
嗯。就像openvpn，好像有这个功能。但是openvpn现在容易被河蟹，而且配置文件太麻烦了。

**Comment by cfcboy** [comment]
嗯。还有就是client1和client2之间，可以ping通。

当然，只是建议哈。

**Comment by wangyu-** [comment]
TinyFecVPN server只接受一个client的连接，后连接的client会把新的挤掉。

>还有就是client1和client2之间，可以ping通。

如果你需要复杂的功能，可以用UDPspeeder+其他VPN

**Comment by wangyu-** [comment]
多开多个server可以支持多个client，多个client间ping通可以通过添加路由规则实现。

**Comment by cfcboy** [comment]
嗯。好的，了解了。谢谢你的解答。
