### ISSUE TITLE
Can't tinyvpn_arm using in Android?

### ISSUE THREAD

**Issue by qwIvan** [wangyu-/tinyFecVPN#24]
[2017-11-22 16:42:24][FATAL]open /dev/net/tun failed

**Comment by wangyu-** [comment]
duplicated with:

https://github.com/wangyu-/tinyFecVPN/issues/1

You can bypass this error by 

```
mkdir /dev/net
ln dev/tun /dev/net/tun
```

Then the program can be run successfully. But seems like its still unusable.
