### ISSUE TITLE
希望tinyFecVPN 可以增加 --cipher-mode 参数

### ISSUE THREAD

**Issue by digitbear** [wangyu-/tinyFecVPN#29]
大神，您好，提个小小的建议， 希望tinyFecVPN 可以增加 --cipher-mode 参数，增加其他加密选项 ，比如 aes128cbc ，比如 chacha20 ，感谢。

**Comment by wangyu-** [comment]
tinyFecVPN就像l2tp一样，只提供VPN功能，不提供加密/提供弱加密。

加密功能由其他程序提供，比如你可以在tinyFecVPN前面套个udp2raw或者socat，使用udp2raw/socat的加密。

**Comment by digitbear** [comment]
明白了，谢谢！
