### ISSUE TITLE
关于--disable-fec后的MTU设置

### ISSUE THREAD

**Issue by rockmanx1122** [wangyu-/tinyFecVPN#34]
当启动参数--disable-fec后，该如何设置MTU（电脑以及tinyvpn服务端与客户端）的相关数值才是最佳的呢？

**Comment by wangyu-** [comment]
没有最佳的，下面的设置仅供参考。

建议不使用`--disable-fec`而是把冗余设置成0:
```
./tinyvpn_amd64 -s -l 0.0.0.0:5533 --mode 0 -f2:0
./tinyvpn_amd64 -c -r 44.55.66.77:5533 --mode 0 -f2:0
```

如果一定要`--disable-fec`的话也可以:
```
./tinyvpn_amd64 -s -l 0.0.0.0:5533 `--disable-fec` --tun-mtu 1250
./tinyvpn_amd64 -c -r 44.55.66.77:5533 `--disable-fec` --tun-mtu 1250
```
(加上`--disable-fec`以后`--mtu`参数不起作用，需要用`--tun-mtu`)

**Comment by rockmanx1122** [comment]
谢谢大大，但是我还想再问问有玩游戏的推荐设置吗？

**Comment by wangyu-** [comment]
--fix-lantency实验性质比较强，不要用了，推荐设置参考：

https://github.com/wangyu-/UDPspeeder/wiki/推荐设置

**Comment by rockmanx1122** [comment]
我还想问一问大大关于游戏内不同的延迟检测的问题，比如BF4一样，他的进入游戏后TAB面板出现的是ICMP测试（也许可能是tcp）的ping，但是其实游戏内能够打开网络图标，网络图标内的延迟检测是UDP的，但是不知道为什么两者总是会有差异，一般都是TAB面板上的ping值高出网络图标内的，这样子的话我如何知道到底游戏的TCP或者UDP甚至是ICMP有无被加速呢？
