### ISSUE TITLE
虚拟机tinyVPN可以使用，套上udp2raw无法接通

### ISSUE THREAD

**Issue by vionni** [wangyu-/tinyFecVPN#36]
只有tinyvpn的时候 vps和虚拟机10.22.22.1/10.22.22.2可以互ping成功。
套上udp2raw后一直测试不成功，各位大佬麻烦帮忙看下哪里出错了：

#server 
nohup ./udp2raw/udp2raw_amd64 -s -l0.0.0.0:9966 -r 127.0.0.1:8090  -a -k  “wocem” --raw-mode faketcp -lower-level auto &
nohup ./tinyvpn/tinyvpn_amd64 -s -l 0.0.0.0:8090 -f20:10 -k "passwd" --sub-net 10.22.22.0  &

#virtualbox
nohup ./udp2raw/udp2raw_x86 -c  -r xx.xx.xx.xx:9966 -l 127.0.0.1:8090 -a -k  “wocem”  --raw-mode faketcp  -lower-level auto   &
nohup ./tinyvpn/tinyvpn_x86 -c -r0.0.0.0.0:8090  -f20:10 -k "passwd" -- sub-net 10.22.22.0  &

已经根据别的Issue，wangyu提示两边都加 -lower-level auto，iptables也按照wiki方法清空了
server IP:xx.xx.xx.xx

**Comment by wangyu-** [comment]
`./tinyvpn/tinyvpn_x86 -c -r0.0.0.0.0:8090 -f20:10 -k "passwd" -- sub-net 10.22.22.0`

`-r0.0.0.0.0:8090`改成`-r127.0.0.1:8090 `

为什么`-- sub-net`之间有空格？

**Comment by wangyu-** [comment]
低级错误太多，没有按照issue guide要求贴出log。关了。
