### ISSUE TITLE
按说明配置，如何判断加速效果

### ISSUE THREAD

**Issue by bzadhere** [wangyu-/tinyFecVPN#37]
参考“tinyFecVPN运行在虚拟机中，加速windows和局域网内其他主机的网络” 说明，按照步骤配置很顺利。
vps 是vultr.com的，位置在日本。在windows上设置虚拟机地址作为网关，从windows ping到vps结果来看，没有提升速度和丢包率。

**Comment by wangyu-** [comment]
用ping测试丢包基本上可以。

>参考“tinyFecVPN运行在虚拟机中，加速windows和局域网内其他主机的网络” 说明，按照步骤配置很顺利

贴出完整的配置，否则别人没法知道你配置对了没有。

>没有提升速度和丢包率。

贴出具体数据。

https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看

**Comment by bzadhere** [comment]
多谢回复，经多次测试确认是windows主机侧网络带宽限制。
