### ISSUE TITLE
碰到几个小问题，厚颜无耻地来请教了

### ISSUE THREAD

**Issue by Dreamone1** [wangyu-/tinyFecVPN#40]
在wiki页面中 https://github.com/wangyu-/tinyFecVPN/wiki/tinyFecVPN%E8%BF%90%E8%A1%8C%E5%9C%A8%E8%99%9A%E6%8B%9F%E6%9C%BA%E4%B8%AD%EF%BC%8C%E5%8A%A0%E9%80%9Fwindows%E5%92%8C%E5%B1%80%E5%9F%9F%E7%BD%91%E5%86%85%E5%85%B6%E4%BB%96%E4%B8%BB%E6%9C%BA%E7%9A%84%E7%BD%91%E7%BB%9C
问题：
1.“可选命令”这个选项应该是运行在服务端还是客户端，还是需要两边都运行？
2.下载了虚拟机和lede固件，但是在ssh状态下运行客户端的命令的时候，提示我无权限。我搜索了linux命令好像不适用，谷歌百度我都有搜索，我都没有搜索到相关信息。这个应该如何解决？

**Comment by wangyu-** [comment]
>1.“可选命令”这个选项应该是运行在服务端还是客户端，还是需要两边都运行？

在两边都是可选的。

>2.下载了虚拟机和lede固件，但是在ssh状态下运行客户端的命令的时候，提示我无权限。我搜索了linux命令好像不适用，谷歌百度我都有搜索，我都没有搜索到相关信息。这个应该如何解决？

不知道你说的无权限是啥。截个图？

**Comment by Dreamone1** [comment]
哈，搞定了，我试了一下用winscp之中改权限，现在可以用了，谢谢大佬解答！
