### ISSUE TITLE
请教网吧两条VPS线路吃鸡加速方案

### ISSUE THREAD

**Issue by PQFitz** [wangyu-/tinyfecVPN#46]
看了WIKI好像没有网吧加速吃鸡的例子，尤其是2台vps的情况。 想请教一下有方案可以这么做吗？

现在有香港vps与韩国vps两台。

韩国的服务器加速KR/JP,ASIA。
香港vps加速其他地区。

路由器是ER6300G2，WAN口接的R7800（刷lede）做策略和加速功能。

如果想做针对吃鸡的加速，应该在路由器上怎么设置呢，有方案吗？

**Comment by wangyu-** [comment]
两条线路就建立两条VPN。

然后策略路由用`ip route`来做，你这种是非常基本的策略路由，只需要`ip route`这一个命令就能搞定。

只需要把对应的ip段加到路由表里就行了，例如：
```
ip route add x.x.x.x/24 via <gateway_of_vpn1>  dev tun100
ip route add y.y.y.y/16 via <gateway_of_vpn1>  dev tun100
....
ip route add a.a.a.a/20 via <gateway_of_vpn2>  dev tun101
ip route add b.b.b.b/24 via <gateway_of_vpn2>  dev tun101
```

在wiki的教程基础上自己稍微改一下。

如果你需要更复杂的功能，比如只加速吃鸡的端口不加速别的端口，就用 `iptables+ip rule+ ip route`。

**Comment by PQFitz** [comment]
感谢了
小白豁然开朗
现在就试试去
