### ISSUE TITLE
请问路由器拨tinyfecVPN后，怎么单独加速下游pc到服务器的tcp应用

### ISSUE THREAD

**Issue by hxhxd** [wangyu-/tinyfecVPN#49]
作者您好，

我目前在路由器上连udp2raw + tinyfecVPN成功，路由器成功获得10.222.2.2的ip，
路由器ping 10.222.2.1 成功，可以连接。  
而路由器下接的pc此时ping 10.222.2.2是成功的，
但我想pc再去连10.222.2.1失败。  

请问我该怎么操作才能让pc可以连接10.222.2.1，以达到加速某tcp应用的目的（当前是想尝试加速v2ray)。  
可否简单指一下路？ 谢谢 ：）  

目前尝试过在路由器上加
ip route add 10.222.2.0/24 via 10.222.2.2 dev tun100  
在pc上 route add 10.222.2.1 mask 255.255.255.255 10.222.2.2  
均不起作用。

**Comment by wangyu-** [comment]
最简单的方法：
https://github.com/wangyu-/tinyfecVPN/wiki/透过tinyfecVPN免改iptables加速网络

路由表的方法也是可以的。只是你没弄对。

**Comment by hxhxd** [comment]
好的。  
通过这工具映射后，能用了。  
谢谢 ：）
