### ISSUE TITLE
不支持多客户端连接

### ISSUE THREAD

**Issue by renothing** [wangyu-/tinyFecVPN#5]
1：貌似subnet不支持正常的cdir写法？
2：无法多个client同时链接。后期是否打算支持一堆多，多对多的模式？p2p组建虚拟网，类似fcn和peervpn那样的。可以组建lan over nat.前提是现在的tun换成tap。支持arp广播。
用在多服务器间互通隧道很好用。只需一个节点有公网ip足以

**Comment by wangyu-** [comment]
>1：貌似subnet不支持正常的cdir写法？

现在一个server只支持一个client，也就是子网里只能有2台主机，支持10.22.22.0/24这种写法也没什么用了。现在写法为了简单，就规定为xxx.xxx.xxx.0这种方式的。

> 2：无法多个client同时链接。后期是否打算支持一堆多，多对多的模式？p2p组建虚拟网，类似fcn和peervpn那样的。可以组建lan over nat.前提是现在的tun换成tap。支持arp广播。
用在多服务器间互通隧道很好用。只需一个节点有公网ip足以

暂时没有计划。如果需要复杂的功能，还是用UDPspeeder + OpenVPN这种方式吧。
