### ISSUE TITLE
Port Number

### ISSUE THREAD

**Issue by fritz-mueller** [wangyu-/tinyfecVPN#52]
There is a mismatch of port number in your README.md:

Assume your server ip is 44.55.66.77, you have a service listening on udp/tcp port 0.0.0.0:**7777**.

# Run at server side:
./tinyvpn -s -l0.0.0.0:**4096** -f20:10 -k "passwd" --sub-net 10.22.22.0

# Run at client side
./tinyvpn -c -r44.55.66.77:**4096** -f20:10 -k "passwd" --sub-net 10.22.22.0

Now, use 10.22.22.1:**7777** to connect to your service,all traffic will be improved by FEC. If you ping 10.22.22.1, you will get ping reply.

Or am I missing something?

**Comment by wangyu-** [comment]
>Or am I missing something?

I'm afraid yes.

`4096` is tinyfecVPN's own port number.  `7777` is another port at which a "up-level" service is listening.

**Comment by fritz-mueller** [comment]
Oops sorry for the misunderstanding, and thanks for the quick response.
Rainer
