### ISSUE TITLE
20180803.0 版的源代码无法git clone下来无法正常编译

### ISSUE THREAD

**Issue by hdstar2009** [wangyu-/tinyfecVPN#67]
For English speaking user：
https://github.com/wangyu-/UDPspeeder/wiki/Issue-Guide

中文用户请看：
https://github.com/wangyu-/UDPspeeder/wiki/发Issue前请看
(否则Issue可能被忽略，或被直接关掉)

编译最新的那个0820的pre-release版没问题，udpspeeder目录下的文件能clone回来。但是由于新版的文件比0803大很多加上是pre版，所以还是想用0803稳定版。
但是发现 git clone -b 20180803.0 --recursive https://github.com/wangyu-/tinyfecVPN.git
clone回来的目录不包括UDPspeeder目录下的文件，这样编译时候会报错。
直接网站上切换到tag:20180803.0下载zip包同样不包括UDPspeeder目录下的文件。

不是it专业，所以百度和谷歌过，没发现问题所在。发个issue来寻求帮助。

**Comment by hdstar2009** [comment]
自己乱折腾，找到解决办法了。
在teinyfecvpn的20100803.0下点那个UDPspeeder会进入配套的UDPspeeder，下载那个zip文件，也就是下载https://codeload.github.com/wangyu-/UDPspeeder/zip/abe55c02d5f390285a93bc50c3548204e28821fb
然后上传到vps上解压后改目录名UDPspeeder放到tinyfecVPN里面再make就成功了。

**Comment by wangyu-** [comment]
省空间最好的方法是动态编译+strip。

动态编译看这里：
https://github.com/wangyu-/tinyPortMapper/wiki/How-to-build 

strip自己google一下(先编译再`strip`，或者编译时候直接用`g++ -s`)
