### ISSUE TITLE
隔几十分钟就会断流，自动重连的参数不能使用

### ISSUE THREAD

**Issue by otkmaster** [wangyu-/tinyFecVPN#7]
./tinyvpn: unrecognized option '--re-connect'
[2017-11-01 03:13:45][FATAL]unknown option <3f>

**Comment by wangyu-** [comment]
是 `--keep-reconnect` ，--help里面的信息写错了，不好意思。readme里面的是对的。

**Comment by wangyu-** [comment]
已修正。
