### ISSUE TITLE
有关于wiki的一些疑问

### ISSUE THREAD

**Issue by terrytw** [wangyu-/tinyfecVPN#72]
作者你好

我参照
https://github.com/wangyu-/tinyfecVPN/wiki/tinyfecVPN%E8%BF%90%E8%A1%8C%E5%9C%A8%E8%99%9A%E6%8B%9F%E6%9C%BA%E4%B8%AD%EF%BC%8C%E5%8A%A0%E9%80%9Fwindows%E5%92%8C%E5%B1%80%E5%9F%9F%E7%BD%91%E5%86%85%E5%85%B6%E4%BB%96%E4%B8%BB%E6%9C%BA%E7%9A%84%E7%BD%91%E7%BB%9C

进行设置，有一点不太明白的地方，你提到：

> 你只要在windows上把网关改成虚拟机的ip，dns改成8.8.8.8，就可以通过tinyfecVPN加速你的网络了，所有流量都会被重定向。

1. 请问这里的DNS一定要8.8.8.8吗？如果VPS是国内的，用一些国内的常用VPS如114是否也可以？

2. 原有本机的网络情况是自动获取IP，
IP：172.26.170.33
网关：172.26.175.254
MASK：255.255.248.0
虚拟机IP：172.26.170.68

    那么现在改成手动的话，这样写是否可以：
    IP：172.26.170.33
    网关：172.26.170.68
    MASK：255.255.248.0

**Comment by luodaoyi** [comment]
其实很简单  windows吧网关改为虚拟机的ip 作用其实就是加了一条路由而已
```
ip r add 0/0 虚拟机ip
```

也就是本机流量通过虚拟机转发出去

dns随便改咯
然后ip想改什么都可以 只要虚拟机的网关知道你本机的ip就行了。其实ip就是个标识，本地你想改什么都可以。但是出了网关没人任就被丢弃了
