### ISSUE TITLE
L2TP不行

### ISSUE THREAD

**Issue by squallgai** [wangyu-/tinyFecVPN#8]
端口转发都用了。SS这些没问题。但是转发L2TP不行，始终无法连接。。同样的设置。就换了端口。。L2TP始终无法使用。是我哪里设置错了吗？

**Comment by wangyu-** [comment]
你现在的用法是VPN套VPN？

这种特殊用法必须添加一条路由例外，防止tinyFecVPN的流量被L2TP劫持，见下面这个连接：

https://github.com/wangyu-/UDPspeeder/blob/master/doc/udpspeeder_openvpn.md#note

这个讲的是怎么让OpenVPN不劫持UDPspeeder的流量，VPN套VPN也是一样的道理。

**Comment by squallgai** [comment]
是这个意思。这个vpn差不多建立一个通道嘛。。SS的端口都可以，我以为1701这个端口也行。添加了例外一条路由还是不行。。直连vps可以。通过这个中转就不行了。好比vps没有开放L2TP一样

**Comment by wangyu-** [comment]
检查一下l2pt是否bind到了0.0.0.0

如果还不行，清空两端所有iptable再试。

**Comment by wangyu-** [comment]
还有检查一下l2tp的mtu设置，建议设置到1200以下。

**Comment by squallgai** [comment]
L2TP刚才用1460的时候客户端直接报错说太短。
message too long len=1473 fec_mtu=1460,ignored，改成1500就好了。而且玩游戏用1400以下也是报错，改成1460以上才可以

**Comment by squallgai** [comment]
就是连接无响应，应该bind到了0.0.0.0，可能gfw有干扰也不一定。其他软件都可以连接上。包括openvpn..

**Comment by squallgai** [comment]
对了，用kcptun+udpspeeder的时候L2TP也不行。。SS怎么弄都可以

**Comment by wangyu-** [comment]
>L2TP刚才用1460的时候客户端直接报错说太短。
message too long len=1473 fec_mtu=1460,ignored，改成1500就好了。而且玩游戏用1400以下也是报错，改成1460以上才可以

你用了，--mode 1 ?

**Comment by squallgai** [comment]
是的。。不是mode 1速度快一点吗

**Comment by wangyu-** [comment]
>L2TP刚才用1460的时候客户端直接报错说太短。
message too long len=1473 fec_mtu=1460,ignored，改成1500就好了。而且玩游戏用1400以下也是报错，改成1460以上才可以

你把tinyFecVPN加上了--mode 1然后 mtu 改成了1460和1500？能用就怪了。如果不懂mtu是什么的话，老老实实用默认参数。

**Comment by wangyu-** [comment]
> 还有检查一下l2tp的mtu设置，建议设置到1200以下。

我跟你说的是改l2tp里面的mtu，不是改tinyFecVPN的。

**Comment by squallgai** [comment]
L2TP 的MTU里面改成1200，tinyFecVPN用默认的，L2TP连接还是没有响应，SS能连接

**Comment by squallgai** [comment]
bind里面L2TP的1701，4500，500，都在0.0.0.0

**Comment by wangyu-** [comment]
贴出两边tinyFecVPN和L2TP的完整命令、配置和log，贴出两边iptables-save和netstat -nlp的完整输出。

**Comment by squallgai** [comment]
可以了，是我的iptables之前的添加的一个命令没有删除掉。。
ip route del 44.55.66.77 dev tun242
这个添加上去后连接不上，删除掉就可以连接，而且能上了
谢谢大佬了。。麻烦你这么久

**Comment by wangyu-** [comment]
没事。

如果用mode 1的话，保持tinyFecVPN的默认MTU不变，调整l2tp的MTU到1200以下。确保tinyFecVPN里不报MTU的WARN，就可以了。

**Comment by squallgai** [comment]
好的。我用ss-tap用mode 1，不改变mtu的话会提示message too long len=1473，是不是ss服务端里面哪里也要设置的

**Comment by wangyu-** [comment]
>好的。我用ss-tap用mode 1，不改变mtu的话会提示message too long len=1473，是不是ss服务端里面哪里也要设置的

这个不是s***服务端控制的，应该是ss-tap控制的。我瞅了一眼ss-tap的设置页面，貌似ss-tap不支持设置mtu，那还是用mode 0吧。 mode 0会自动切分数据，不用操心MTU，只是延迟大一点点。

**Comment by wangyu-** [comment]
可以看一下README.md里面这一节：

>如果你是开发者，对于--mode 1可以尝试--tun-mtu，把设备mtu设置成和--mtu相同的值(如果没设置过--mtu就把--tun-mtu设成默认的1250)，这样可以使内核对ip包分片（只适用于允许分片的数据包），达到传输巨大的UDP数据包的目的。新手不建议用。

如果用不明白就算了。

**Comment by squallgai** [comment]
好的，就一个玩游戏的，学下，谢谢大神，我自己再研究研究...
