### ISSUE TITLE
可否出个icmp版本，来回流量走icmp，不走udp,走udp还是会被干扰，延迟比较大

### ISSUE THREAD

**Issue by 888001** [wangyu-/tinyfecVPN#98]
English Only (except for bug reporting).

**Comment by 888001** [comment]
tinyfecVPN 客户端跟服务端之间流量传输协议可否支持icmp模式。国内会出现icmp ping国外服务器要比udp ping国外服务器延迟低高，如果tinyfecVPN 支持icmp那么用来加速游戏就完美了

**Comment by wangyu-** [comment]
udp2raw是用来干什么的？
